sudo: required
services:
  - docker

before_install:
# ./client is very important as the build has to be done inside the client context
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client
# here could be added more docker build to prepare the container for further tests
script:
  - docker run stephengrider/react-test npm test -- --coverage

  # do production version build with prod docker filt
after_success:
  - docker build -t vitkoczi/multi-client ./client	
  - docker build -t vitkoczi/multi-nginx ./nginx	
  - docker build -t vitkoczi/multi-server ./server	
  - docker build -t vitkoczi/multi-worker ./worker	
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vitkoczi/multi-client
  - docker push vitkoczi/multi-nginx
  - docker push vitkoczi/multi-server
  - docker push vitkoczi/multi-worker

